# jsPsych Extensions

## Experiment: Lexical Competition with the Visual World Paradigm (eye-tracking)

Participants are shown a 2x2 set of images on the screen and are simultaneously presented with a spoken sentence (e.g. The birthday cake would be ready as soon as he added the candles). There is a key word, the target (e.g. candles), that is spoken at the end of the sentence and is presented as one of the images. The other 3 images are (1) a phonological competitor (e.g. candy), (2) a semantic competitor (e.g. frosting), and (3) an unrelated filler (e.g. tape). Eye-tracking data during this task reveals lexical prediction and competition during online sentence listening.

Key topics covered:
- Using the jsPsych eye-tracking extension

## Experiment: Regressions to Ambiguities During Sentence Reading (MouseView)

Participants are shown written sentences containing lexical-semantic ambiguities. Sometimes the end of the sentence disambiguates the ambiguous word (e.g. ball) toward the subordinate (less-frequent) meaning (e.g. "Sally worried that the ball was going to be too crowded.") and sometimes the final word is compatible with the dominant meaning ("expensive"). These sentences are presented on the screen while using the MouseView extension, which tracks visual attention over time by hiding/blurring the page content but providing a small viewing window (aperture) that is controlled by the mouse. The participant reads each sentence by positioning the mouse on the left-hand side of the sentence and moving it toward the right as they read. The dependent measure is the frequency of regressions back to the ambiguous word after reaching the disambiguating word at the end of the sentence.

Key topics covered:
- Using the jsPsych MouseView extension