---
title: "Online Behavioral Experiments with jsPsych"
author: "Joshua R. de Leeuw"
site: bookdown::bookdown_site
documentclass: book
output:
  bookdown::gitbook:
    split_by: 'section'
---

```{r, include=FALSE}
if(!dir.exists('docs/demos')) { dir.create('docs/demos') }
file.copy('demos', 'docs', recursive = T, overwrite = T)
```

# Welcome {-}
  
This book will teach you how to create behavioral experiments using [jsPsych](https://www.jspsych.org). jsPsych is a JavaScript-based framework for developing experiments that run in a web browser. Any device (e.g., desktops, laptops, tablets, and mobile phones) with a modern web browser installed can run jsPsych experiments with no additional installation necessary. Experiments can be delivered via a web server for online participants, or run locally on a computer in a laboratory. 

Each chapter of this book illustrates a key feature or set of related features of jsPsych by walking you through the creation of a real experiment from the cognitive science literature. If you are brand new to jsPsych (or web-based programming in general), it's recommended that you work through the chapters in order. Experiments later in the book build off the concepts introduced by earlier experiments. If you are already familiar with jsPsych and are looking to learn about a specific technique, each chapter should be sufficiently self-contained that you can jump around.

This book is licensed under the [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License](http://creativecommons.org/licenses/by-nc-sa/4.0/). Suggestions, requests for clarification, corrections, and contributions are welcome! Please use the [Issue Tracker in the book's GitHub repository](https://github.com/jspsych/webbook/issues) or open a [pull request](https://github.com/jspsych/webbook/pulls).

This book is written in [RMarkdown](https://rmarkdown.rstudio.com/) with [bookdown](https://bookdown.org/yihui/bookdown/).